Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.hostname = "vague-router3"

  config.vm.network "forwarded_port", guest: 22, host: 22116, id: 'ssh'
  config.ssh.insert_key = true

  config.vm.network "private_network", ip: "192.168.16.254", virtualbox__intnet: "intnet-3", netmask: "255.255.252.0"
  #config.vm.network "private_network", ip: "192.168.101.1", virtualbox__intnet: "intnet-101"
  #config.vm.network "private_network", ip: "192.168.102.1", virtualbox__intnet: "intnet-102"

  config.vm.network "private_network", ip: "192.168.24.1", virtualbox__intnet: "intnet-101", netmask: "255.255.252.0"
  config.vm.network "private_network", ip: "192.168.28.1", virtualbox__intnet: "intnet-102", netmask: "255.255.252.0"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vague-router3"
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  end

  config.vm.provision :shell, path: "setup_net.sh"

end
