# -*- mode: ruby -*-

# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.hostname = "vague-router4"


  config.vm.network "forwarded_port", guest: 22, host: 22119, id: 'ssh'

  config.ssh.insert_key = true
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.4.254", virtualbox__intnet: "intnet-4"
  config.vm.network "private_network", ip: "192.168.101.1", virtualbox__intnet: "intnet-101"
  config.vm.network "private_network", ip: "192.168.103.2", virtualbox__intnet: "intnet-103"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vague-router4"
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  end

  config.vm.provision :shell, path: "setup_net.sh"

end
