Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "vague-web-server"

  config.vm.network "forwarded_port", guest: 22, host: 22113, id: 'ssh'
  config.ssh.insert_key = true

  config.vm.network "private_network", ip: "192.168.16.2", virtualbox__intnet: "intnet-3", netmask: "255.255.252.0"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vague-web-server"
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  end

  config.vm.provision :shell, path: "setup_net.sh"

end
