Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "vague-attacker"

  config.vm.network "forwarded_port", guest: 22, host: 22112, id: 'ssh'
  config.ssh.insert_key = true

  config.vm.network "private_network", ip: "192.168.2.2", virtualbox__intnet: "intnet-2", netmask: "255.255.252.0"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vague-attacker"
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  end

  config.vm.provision :shell, path: "setup_net.sh"

  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
