# -*- mode: ruby -*-

# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "vague-router1"

  config.vm.network "forwarded_port", guest: 22, host: 22116, id: 'ssh'

  config.ssh.insert_key = true

  config.vm.network "private_network", ip: "192.168.1.254", virtualbox__intnet: "intnet-1"
  config.vm.network "private_network", ip: "192.168.100.1", virtualbox__intnet: "intnet-100"
  config.vm.network "private_network", ip: "192.168.101.2", virtualbox__intnet: "intnet-101"


  #
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vague-router1"
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  end

  config.vm.provision :shell, path: "setup_net.sh"

end
