Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.hostname = "vague-router2"
  config.vm.network "forwarded_port", guest: 22, host: 22115, id: 'ssh'

  config.ssh.insert_key = true

  config.vm.network "private_network", ip: "192.168.2.254", virtualbox__intnet: "intnet-2", netmask: "255.255.252.0"
  #config.vm.network "private_network", ip: "192.168.100.2", virtualbox__intnet: "intnet-100"
  #config.vm.network "private_network", ip: "192.168.102.2", virtualbox__intnet: "intnet-102"

  config.vm.network "private_network", ip: "192.168.20.2", virtualbox__intnet: "intnet-100", netmask: "255.255.252.0"
  config.vm.network "private_network", ip: "192.168.28.2", virtualbox__intnet: "intnet-102", netmask: "255.255.252.0"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vague-router2"
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  end

  config.vm.provision :shell, path: "setup_net.sh"

end
