# -*- mode: ruby -*-

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "vague-client"

  config.vm.network "forwarded_port", guest: 22, host: 22114, id: 'ssh'
  config.ssh.insert_key = true

  config.vm.network "private_network", ip: "192.168.4.2", virtualbox__intnet: "intnet-5"

  #
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vague-client"
  end

  #config.vm.provision :shell, path: "setup_net.sh"

end
